AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auto Lab Solutions - Complete Backend Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: production
    Description: Environment name
  
  S3BucketName:
    Type: String
    Default: auto-lab-reports
    Description: S3 bucket name for reports
  
  CloudFormationBucket:
    Type: String
    Default: auto-lab-cloudformation-templates
    Description: S3 bucket containing CloudFormation templates and Lambda packages

  StripeSecretKey:
    Type: String
    NoEcho: true
    Description: Stripe secret key for payment processing
  
  StripeWebhookSecret:
    Type: String
    NoEcho: true
    Description: Stripe webhook endpoint secret for signature verification

  Auth0Domain:
    Type: String
    NoEcho: true
    Description: Auth0 domain for authentication
    Default: ""

  Auth0Audience:
    Type: String
    NoEcho: true
    Description: Auth0 API audience for token validation
    Default: ""

  ReportsBucketName:
    Type: String
    Description: S3 bucket name for storing reports
    Default: ""

  SharedKey:
    Type: String
    NoEcho: true
    Description: Shared key for internal communication
    Default: ""

  FrontendRootUrl:
    Type: String
    Description: Frontend root URL for invoice links and QR codes
    Default: ""

  # Frontend Website Parameters
  EnableFrontendWebsite:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Whether to deploy the frontend website

  FrontendDomainName:
    Type: String
    Description: The full domain name for the frontend website (leave empty for development)
    Default: ''

  FrontendHostedZoneId:
    Type: String
    Description: The ID of the Route53 hosted zone for frontend domain (leave empty to skip Route53)
    Default: ''

  FrontendAcmCertificateArn:
    Type: String
    Description: ARN of the ACM certificate in us-east-1 for frontend domain (leave empty for development)
    Default: ''

  EnableCustomDomain:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Whether to enable custom domain for frontend

Conditions:
  ShouldDeployFrontend: !Equals [!Ref EnableFrontendWebsite, 'true']

Resources:
  # DynamoDB Tables
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucket}.s3.amazonaws.com/dynamodb-tables.yaml'
      Parameters:
        Environment: !Ref Environment

  # Lambda Functions
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - DynamoDBStack
      - S3CloudFrontStack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucket}.s3.amazonaws.com/lambda-functions.yaml'
      Parameters:
        Environment: !Ref Environment
        CloudFormationBucket: !Ref CloudFormationBucket
        StaffTable: !GetAtt DynamoDBStack.Outputs.StaffTable
        UsersTable: !GetAtt DynamoDBStack.Outputs.UsersTable
        ConnectionsTable: !GetAtt DynamoDBStack.Outputs.ConnectionsTable
        MessagesTable: !GetAtt DynamoDBStack.Outputs.MessagesTable
        UnavailableSlotsTable: !GetAtt DynamoDBStack.Outputs.UnavailableSlotsTable
        AppointmentsTable: !GetAtt DynamoDBStack.Outputs.AppointmentsTable
        ServicePricesTable: !GetAtt DynamoDBStack.Outputs.ServicePricesTable
        OrdersTable: !GetAtt DynamoDBStack.Outputs.OrdersTable
        ItemPricesTable: !GetAtt DynamoDBStack.Outputs.ItemPricesTable
        InquiriesTable: !GetAtt DynamoDBStack.Outputs.InquiriesTable
        PaymentsTable: !GetAtt DynamoDBStack.Outputs.PaymentsTable
        InvoicesTable: !GetAtt DynamoDBStack.Outputs.InvoicesTable
        StripeSecretKey: !Ref StripeSecretKey
        StripeWebhookSecret: !Ref StripeWebhookSecret
        Auth0Domain: !Ref Auth0Domain
        Auth0Audience: !Ref Auth0Audience
        CloudFrontDomain: !GetAtt S3CloudFrontStack.Outputs.CloudFrontDomainName
        ReportsBucketName: !Sub 'auto-lab-reports-${AWS::AccountId}-${Environment}'
        FrontendRootUrl: !Ref FrontendRootUrl
        SharedKey: !Ref SharedKey

  # API Gateway
  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaStack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucket}.s3.amazonaws.com/api-gateway.yaml'
      Parameters:
        Environment: !Ref Environment
        StaffAuthorizerArn: !GetAtt LambdaStack.Outputs.StaffAuthorizerArn
        StaffAuthorizerOptionalArn: !GetAtt LambdaStack.Outputs.StaffAuthorizerOptionalArn
        GetPricesArn: !GetAtt LambdaStack.Outputs.GetPricesArn
        GetUsersArn: !GetAtt LambdaStack.Outputs.GetUsersArn
        GetAppointmentsArn: !GetAtt LambdaStack.Outputs.GetAppointmentsArn
        CreateAppointmentArn: !GetAtt LambdaStack.Outputs.CreateAppointmentArn
        UpdateAppointmentArn: !GetAtt LambdaStack.Outputs.UpdateAppointmentArn
        GetUnavailableSlotsArn: !GetAtt LambdaStack.Outputs.GetUnavailableSlotsArn
        UpdateUnavailableSlotsArn: !GetAtt LambdaStack.Outputs.UpdateUnavailableSlotsArn
        GetOrdersArn: !GetAtt LambdaStack.Outputs.GetOrdersArn
        CreateOrderArn: !GetAtt LambdaStack.Outputs.CreateOrderArn
        UpdateOrderArn: !GetAtt LambdaStack.Outputs.UpdateOrderArn
        ConfirmCashPaymentArn: !GetAtt LambdaStack.Outputs.ConfirmCashPaymentArn
        CreatePaymentIntentArn: !GetAtt LambdaStack.Outputs.CreatePaymentIntentArn
        ConfirmStripePaymentArn: !GetAtt LambdaStack.Outputs.ConfirmStripePaymentArn
        WebhookStripePaymentArn: !GetAtt LambdaStack.Outputs.WebhookStripePaymentArn
        GetInquiriesArn: !GetAtt LambdaStack.Outputs.GetInquiriesArn
        CreateInquiryArn: !GetAtt LambdaStack.Outputs.CreateInquiryArn
        GetReportUploadUrlArn: !GetAtt LambdaStack.Outputs.GetReportUploadUrlArn
        GetAnalyticsArn: !GetAtt LambdaStack.Outputs.GetAnalyticsArn
        GetStaffRolesArn: !GetAtt LambdaStack.Outputs.GetStaffRolesArn
        NotifyArn: !GetAtt LambdaStack.Outputs.NotifyArn
        TakeUserArn: !GetAtt LambdaStack.Outputs.TakeUserArn
        GetConnectionsArn: !GetAtt LambdaStack.Outputs.GetConnectionsArn
        GetMessagesArn: !GetAtt LambdaStack.Outputs.GetMessagesArn
        GetLastMessagesArn: !GetAtt LambdaStack.Outputs.GetLastMessagesArn
        SendMessageArn: !GetAtt LambdaStack.Outputs.SendMessageArn

  # WebSocket API
  WebSocketStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaStack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucket}.s3.amazonaws.com/websocket-api.yaml'
      Parameters:
        Environment: !Ref Environment
        WsConnectArn: !GetAtt LambdaStack.Outputs.WsConnectArn
        WsDisconnectArn: !GetAtt LambdaStack.Outputs.WsDisconnectArn
        WsInitArn: !GetAtt LambdaStack.Outputs.WsInitArn
        WsPingArn: !GetAtt LambdaStack.Outputs.WsPingArn
        WsStaffInitArn: !GetAtt LambdaStack.Outputs.WsStaffInitArn

  # S3 and CloudFront for Reports
  S3CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucket}.s3.amazonaws.com/s3-cloudfront.yaml'
      Parameters:
        Environment: !Ref Environment
        S3BucketName: !Ref S3BucketName

  # Frontend Website Stack
  FrontendWebsiteStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployFrontend
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucket}.s3.amazonaws.com/frontend-website.yaml'
      Parameters:
        Environment: !Ref Environment
        DomainName: !Ref FrontendDomainName
        HostedZoneId: !Ref FrontendHostedZoneId
        AcmCertificateArn: !Ref FrontendAcmCertificateArn
        EnableCustomDomain: !Ref EnableCustomDomain

Outputs:
  RestApiId:
    Description: REST API ID
    Value: !GetAtt ApiGatewayStack.Outputs.RestApiId
    Export:
      Name: !Sub '${AWS::StackName}-RestApiId'

  RestApiEndpoint:
    Description: REST API Endpoint
    Value: !GetAtt ApiGatewayStack.Outputs.RestApiEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-RestApiEndpoint'

  WebSocketApiId:
    Description: WebSocket API ID
    Value: !GetAtt WebSocketStack.Outputs.WebSocketApiId
    Export:
      Name: !Sub '${AWS::StackName}-WebSocketApiId'

  WebSocketApiEndpoint:
    Description: WebSocket API Endpoint
    Value: !GetAtt WebSocketStack.Outputs.WebSocketApiEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-WebSocketApiEndpoint'

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !GetAtt S3CloudFrontStack.Outputs.CloudFrontDistributionId
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  CloudFrontDomainName:
    Description: CloudFront Domain Name
    Value: !GetAtt S3CloudFrontStack.Outputs.CloudFrontDomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomainName'

  # Frontend Website Outputs
  FrontendWebsiteURL:
    Condition: ShouldDeployFrontend
    Description: Frontend Website URL
    Value: !GetAtt FrontendWebsiteStack.Outputs.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-FrontendWebsiteURL'

  FrontendBucketName:
    Condition: ShouldDeployFrontend
    Description: Frontend S3 Bucket Name
    Value: !GetAtt FrontendWebsiteStack.Outputs.WebsiteBucketName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketName'

  FrontendCloudFrontDistributionId:
    Condition: ShouldDeployFrontend
    Description: Frontend CloudFront Distribution ID
    Value: !GetAtt FrontendWebsiteStack.Outputs.CloudFrontDistributionId
    Export:
      Name: !Sub '${AWS::StackName}-FrontendCloudFrontDistributionId'

  FrontendCloudFrontDomainName:
    Condition: ShouldDeployFrontend
    Description: Frontend CloudFront Domain Name
    Value: !GetAtt FrontendWebsiteStack.Outputs.CloudFrontDomainName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendCloudFrontDomainName'

  ApiWebhookStripePaymentUrl:
    Description: Stripe Payment Webhook Public URL
    Value: !Sub '${ApiGatewayStack.Outputs.RestApiEndpoint}/payments/stripe/webhook'
    Export:
      Name: !Sub '${AWS::StackName}-ApiWebhookStripePaymentUrl'
