AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auto Lab Solutions - SES Domain Verification (Simplified)'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name
    Default: production

  SesRegion:
    Type: String
    Description: AWS SES region
    Default: "ap-southeast-2"

  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID (leave empty to skip DNS automation)
    Default: ""

  DomainName:
    Type: String
    Description: Domain name for email receiving
    Default: "autolabsolutions.com"

Conditions:
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, ""]]

Resources:
  # SES Domain Identity - automatically gets verification token
  SESDomainIdentity:
    Type: AWS::SES::DomainIdentity
    Properties:
      Domain: !Ref DomainName

  # Route53 DNS Records for domain verification
  DomainVerificationRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '_amazonses.${DomainName}'
      Type: TXT
      TTL: 300
      ResourceRecords:
        - !Sub '"${SESDomainIdentity.VerificationToken}"'

  # MX Record for Email Receiving
  EmailReceivingMXRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '${DomainName}.'
      Type: MX
      TTL: 300
      ResourceRecords:
        - !Sub '10 inbound-smtp.${SesRegion}.amazonses.com'

Outputs:
  SESDomainIdentity:
    Description: SES Domain Identity for email receiving
    Value: !Ref SESDomainIdentity
    Export:
      Name: !Sub '${AWS::StackName}-SESDomainIdentity'

  SESVerifiedEmail:
    Description: SES Email Identity (same as domain identity)
    Value: !Ref SESDomainIdentity
    Export:
      Name: !Sub '${AWS::StackName}-SESVerifiedEmail'

  DomainName:
    Description: The domain name configured for SES
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'

  VerificationToken:
    Description: SES domain verification token
    Value: !GetAtt SESDomainIdentity.VerificationToken

  DNSRecordsCreated:
    Description: Whether DNS records were automatically created
    Value: !If 
      - HasHostedZone
      - 'true'
      - 'false'

  VerificationStatus:
    Description: Status of the domain verification process
    Value: !If 
      - HasHostedZone
      - 'DNS records created automatically'
      - 'Manual DNS configuration required'
