AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auto Lab Solutions - SES Email Receiving Only (No Notifications)'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name
    Default: production

  SesRegion:
    Type: String
    Description: AWS SES region
    Default: "ap-southeast-2"

  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID
    Default: ""

  DomainName:
    Type: String
    Description: Domain name for email receiving
    Default: "autolabsolutions.com"

  VerificationToken:
    Type: String
    Description: SES domain verification token
    Default: ""

Conditions:
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, ""]]
  HasVerificationToken: !Not [!Equals [!Ref VerificationToken, ""]]

Resources:
  # SES Email Identity for domain - EMAIL RECEIVING ONLY
  SESDomainIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref DomainName

  # Route53 DNS Records for email receiving
  DomainVerificationRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasVerificationToken
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '_amazonses.${DomainName}'
      Type: TXT
      TTL: 300
      ResourceRecords:
        - !Sub '"${VerificationToken}"'

  # MX Record for Email Receiving
  EmailReceivingMXRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: MX
      TTL: 300
      ResourceRecords:
        - !Sub '10 inbound-smtp.${SesRegion}.amazonses.com'

Outputs:
  SESDomainIdentity:
    Description: SES Domain Identity for email receiving
    Value: !Ref SESDomainIdentity
    Export:
      Name: !Sub '${AWS::StackName}-SESDomainIdentity'

  SESVerifiedEmail:
    Description: SES Email Identity (same as domain identity)
    Value: !Ref SESDomainIdentity
    Export:
      Name: !Sub '${AWS::StackName}-SESVerifiedEmail'

  DomainName:
    Description: The domain name configured for SES
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
