AWSTemplateFormatVersion: '2010-09-09'
Description: 'SES Email Storage with S3-triggered Email Processing (No SES Direct Triggers)'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name
    Default: production

  EmailStorageBucketName:
    Type: String
    Description: S3 bucket name for storing received emails
    Default: "auto-lab-email-storage"

  SesRegion:
    Type: String
    Description: AWS SES region (us-east-1 for development, ap-southeast-2 for production)
    Default: "us-east-1"

  MailReceivingAddress:
    Type: String
    Description: Email address used for receiving emails
    Default: "mail@autolabsolutions.com"

  CloudFormationBucket:
    Type: String
    Description: S3 bucket containing Lambda packages
    Default: "auto-lab-cloudformation-templates"

  EmailMetadataTable:
    Type: String
    Description: DynamoDB table for email metadata (managed by DynamoDB stack)
    Default: ""

  EmailThreadsTable:
    Type: String
    Description: DynamoDB table for email threading (managed by DynamoDB stack)
    Default: ""

  EmailAttachmentsTable:
    Type: String
    Description: DynamoDB table for email attachments (managed by DynamoDB stack)
    Default: ""

  EmailAttachmentsBucket:
    Type: String
    Description: S3 bucket for storing email attachments (managed by S3 stack)
    Default: ""

  FirebaseNotificationQueueUrl:
    Type: String
    Description: URL of the Firebase notification SQS queue
    Default: ""

  EnableFirebaseNotifications:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Whether to enable Firebase push notifications

Resources:

  # Email Processor Lambda Function
  EmailProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'email-processor-${EnvironmentName}'
      Runtime: python3.13
      Handler: main.lambda_handler
      Role: !GetAtt EmailProcessorRole.Arn
      Code:
        S3Bucket: !Ref CloudFormationBucket
        S3Key: 'lambda/email-processor.zip'
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
          EMAIL_STORAGE_BUCKET: !Ref EmailStorageBucket
          EMAIL_METADATA_TABLE: !Ref EmailMetadataTable
          EMAIL_THREADS_TABLE: !Ref EmailThreadsTable
          EMAIL_ATTACHMENTS_TABLE: !Ref EmailAttachmentsTable
          EMAIL_ATTACHMENTS_BUCKET: !Ref EmailAttachmentsBucket
          FIREBASE_NOTIFICATION_QUEUE_URL: !Ref FirebaseNotificationQueueUrl
          ENABLE_FIREBASE_NOTIFICATIONS: !Ref EnableFirebaseNotifications
          MAIL_RECEIVING_ADDRESS: !Ref MailReceivingAddress
      Timeout: 60
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: EmailProcessing

  # IAM Role for Email Processor Lambda
  EmailProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EmailProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${EmailStorageBucketName}-${AWS::AccountId}-${EnvironmentName}/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObjectUrl
                Resource: !Sub 'arn:aws:s3:::${EmailAttachmentsBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:HeadBucket
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub 'arn:aws:s3:::${EmailStorageBucketName}-${AWS::AccountId}-${EnvironmentName}'
                  - !Sub 'arn:aws:s3:::${EmailAttachmentsBucket}'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmailMetadataTable}'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmailThreadsTable}'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmailAttachmentsTable}'
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmailThreadsTable}/index/*"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmailMetadataTable}/index/*"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmailAttachmentsTable}/index/*"
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                Resource: "*"  # Using wildcard since we only have queue URL, not ARN

  # Permission for S3 to invoke the Lambda function (will be managed by bash script)
  # Note: This permission is now handled by configure-s3-email-notification.sh script

  # S3 Bucket for storing received emails
  EmailStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EmailStorageBucketName}-${AWS::AccountId}-${EnvironmentName}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldEmails
            Status: Enabled
            ExpirationInDays: 365  # Keep emails for 1 year
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: EmailStorage

  # S3 Bucket Policy to allow SES to write emails
  EmailStorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailStorageBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSESToWriteEmails
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Sub 
              - '${BucketArn}/*'
              - BucketArn: !GetAtt EmailStorageBucket.Arn
            Condition:
              StringEquals:
                'aws:Referer': !Ref 'AWS::AccountId'


  # SES Receipt Rule Set
  SESReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Sub 'auto-lab-email-rules-${EnvironmentName}'

  # SES Receipt Rule for incoming emails
  SESReceiptRule:
    Type: AWS::SES::ReceiptRule
    DependsOn: 
      - EmailStorageBucketPolicy
    Properties:
      RuleSetName: !Ref SESReceiptRuleSet
      Rule:
        Name: !Sub 'auto-lab-email-rule-${EnvironmentName}'
        Enabled: true
        Recipients:
          - !Ref MailReceivingAddress
        Actions:
          - S3Action:
              BucketName: !Ref EmailStorageBucket
              ObjectKeyPrefix: !Sub 'emails/${EnvironmentName}/'
        ScanEnabled: true

  # Lambda function to activate the SES receipt rule set (since CloudFormation doesn't support this directly)
  SESRuleSetActivatorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'ses-ruleset-activator-${EnvironmentName}'
      Runtime: python3.13
      Handler: index.lambda_handler
      Timeout: 60
      Role: !GetAtt SESRuleSetActivatorRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import json
          
          def lambda_handler(event, context):
              try:
                  ses_client = boto3.client('ses')
                  
                  if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
                      rule_set_name = event['ResourceProperties']['RuleSetName']
                      region = event['ResourceProperties']['Region']
                      
                      # Set the rule set as active
                      ses_client.set_active_receipt_rule_set(RuleSetName=rule_set_name)
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                     {'Message': f'Successfully activated rule set: {rule_set_name}'})
                  
                  elif event['RequestType'] == 'Delete':
                      # On delete, we need to deactivate the rule set to allow deletion
                      try:
                          rule_set_name = event['ResourceProperties']['RuleSetName']
                          
                          # Check if this rule set is currently active
                          active_rule_set = ses_client.describe_active_receipt_rule_set()
                          current_active_name = active_rule_set.get('RuleSet', {}).get('Name')
                          
                          if current_active_name == rule_set_name:
                              # This rule set is active, so we need to deactivate it
                              print(f'Deactivating active rule set: {rule_set_name}')
                              ses_client.set_active_receipt_rule_set()  # Call without RuleSetName deactivates all
                              
                              cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                             {'Message': f'Successfully deactivated rule set: {rule_set_name}'})
                          else:
                              # This rule set is not active, safe to proceed
                              cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                             {'Message': f'Rule set {rule_set_name} was not active, no deactivation needed'})
                                             
                      except Exception as delete_error:
                          print(f'Error during delete: {str(delete_error)}')
                          # Even if deactivation fails, we should succeed to allow stack deletion
                          cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                         {'Message': f'Delete completed with warning: {str(delete_error)}'})
                  
              except Exception as e:
                  print(f'Error: {str(e)}')
                  cfnresponse.send(event, context, cfnresponse.FAILED, 
                                 {'Message': f'Failed to manage rule set: {str(e)}'})

  # IAM Role for the SES rule set activator function
  SESRuleSetActivatorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SESRuleSetAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SetActiveReceiptRuleSet
                  - ses:DescribeActiveReceiptRuleSet
                  - ses:ListReceiptRuleSets
                  - ses:DescribeReceiptRuleSet
                Resource: '*'

  # Custom resource to activate the SES receipt rule set
  SESRuleSetActivation:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: SESReceiptRule
    Properties:
      ServiceToken: !GetAtt SESRuleSetActivatorFunction.Arn
      RuleSetName: !Ref SESReceiptRuleSet
      Region: !Ref SesRegion
      MailFromAddress: !Ref MailReceivingAddress

Outputs:
  EmailStorageBucket:
    Description: S3 bucket for storing received emails
    Value: !Ref EmailStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-EmailStorageBucket'

  SESReceiptRuleSet:
    Description: SES receipt rule set name
    Value: !Ref SESReceiptRuleSet
    Export:
      Name: !Sub '${AWS::StackName}-SESReceiptRuleSet'

  EmailProcessorLambdaArn:
    Description: ARN of the Email Processor Lambda function
    Value: !GetAtt EmailProcessorLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EmailProcessorLambdaArn'

  EmailProcessorLambdaName:
    Description: Name of the Email Processor Lambda function
    Value: !Ref EmailProcessorLambda
    Export:
      Name: !Sub '${AWS::StackName}-EmailProcessorLambdaName'
