AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auto Lab Solutions - SES Domain Verification (Simplified)'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name
    Default: production

  SesRegion:
    Type: String
    Description: AWS SES region
    Default: "ap-southeast-2"

  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID (leave empty to skip DNS automation)
    Default: ""

  DomainName:
    Type: String
    Description: Domain name for email receiving
    Default: "autolabsolutions.com"

  VerificationToken:
    Type: String
    Description: SES domain verification token (obtain from AWS Console/CLI)
    Default: ""

Conditions:
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, ""]]
  HasVerificationToken: !Not [!Equals [!Ref VerificationToken, ""]]

Resources:
  # SES Configuration Set for email handling
  SESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub '${AWS::StackName}-config-set'

  # Route53 DNS Records for domain verification
  # Note: VerificationToken must be obtained manually from AWS Console/CLI
  DomainVerificationRecord:
    Type: AWS::Route53::RecordSet
    Condition: !And
      - !Condition HasHostedZone
      - !Condition HasVerificationToken
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '_amazonses.${DomainName}'
      Type: TXT
      TTL: 300
      ResourceRecords:
        - !Sub '"${VerificationToken}"'

  # MX Record for Email Receiving
  EmailReceivingMXRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '${DomainName}.'
      Type: MX
      TTL: 300
      ResourceRecords:
        - !Sub '10 inbound-smtp.${SesRegion}.amazonses.com'

Outputs:
  SESConfigurationSet:
    Description: SES Configuration Set for email handling
    Value: !Ref SESConfigurationSet
    Export:
      Name: !Sub '${AWS::StackName}-SESConfigurationSet'

  DomainName:
    Description: The domain name configured for SES
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'

  VerificationToken:
    Description: SES domain verification token (if provided)
    Value: !Ref VerificationToken
    Condition: HasVerificationToken

  DNSRecordsCreated:
    Description: Whether DNS records were automatically created
    Value: !If 
      - !And
        - !Condition HasHostedZone
        - !Condition HasVerificationToken
      - 'true'
      - 'false'

  VerificationStatus:
    Description: Status of the domain verification process
    Value: !If 
      - !And
        - !Condition HasHostedZone
        - !Condition HasVerificationToken
      - 'DNS records created automatically'
      - 'Manual DNS configuration required'

  ManualSteps:
    Description: Manual steps required for SES domain verification
    Value: !Sub |
      1. Run: aws ses verify-domain-identity --domain ${DomainName} --region ${SesRegion}
      2. Get verification token from the output
      3. Update this stack with the VerificationToken parameter
      4. Verify domain in SES console
