AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS SES Email Receiving and S3 Storage System for Auto Lab Solutions'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (development, production)
    Default: production
    AllowedValues:
      - development
      - production

  EmailStorageBucketName:
    Type: String
    Description: S3 bucket name for storing received emails
    Default: "auto-lab-email-storage"

  SesRegion:
    Type: String
    Description: AWS SES region
    Default: "ap-southeast-2"

  CloudFormationBucket:
    Type: String
    Description: S3 bucket containing CloudFormation templates and Lambda packages
    Default: "auto-lab-cloudformation-templates"

  MailReceivingAddress:
    Type: String
    Description: Email address for receiving emails (environment-specific)
    Default: "mail@autolabsolutions.com"

  EmailMetadataTableName:
    Type: String
    Description: DynamoDB table name for email metadata (including environment suffix)
    Default: "EmailMetadata-production"

Resources:
  # DynamoDB Table to store email metadata for quick queries (no dependencies)
  EmailMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref EmailMetadataTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: message_id
          AttributeType: S
        - AttributeName: to_email
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: from_email
          AttributeType: S
      KeySchema:
        - AttributeName: message_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ToEmailIndex
          KeySchema:
            - AttributeName: to_email
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: FromEmailIndex
          KeySchema:
            - AttributeName: from_email
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: EmailMetadata

  # S3 Bucket for storing received emails (without notification configuration to avoid circular dependency)
  EmailStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EmailStorageBucketName}-${AWS::AccountId}-${EnvironmentName}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldEmails
            Status: Enabled
            ExpirationInDays: 365  # Keep emails for 1 year
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: EmailStorage

  # S3 Bucket Policy to allow SES to put objects
  EmailStorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailStorageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: 
              - s3:PutObject
              - s3:PutObjectAcl
            Resource: !Sub '${EmailStorageBucket.Arn}/*'
            Condition:
              StringEquals:
                'aws:Referer': !Ref 'AWS::AccountId'
          - Sid: AllowSESGetBucketLocation
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: s3:GetBucketLocation
            Resource: !GetAtt EmailStorageBucket.Arn
            Condition:
              StringEquals:
                'aws:Referer': !Ref 'AWS::AccountId'

  # IAM Role for the email processor Lambda
  EmailProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'EmailProcessorRole-${EnvironmentName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${EmailStorageBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt EmailStorageBucket.Arn
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt EmailMetadataTable.Arn

  # Lambda function to process incoming emails
  EmailProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'email-processor-${EnvironmentName}'
      Runtime: python3.12
      Handler: main.lambda_handler
      Role: !GetAtt EmailProcessorRole.Arn
      Timeout: 60
      Code:
        S3Bucket: !Ref CloudFormationBucket
        S3Key: lambda/email-processor.zip
      Environment:
        Variables:
          EMAIL_STORAGE_BUCKET: !Ref EmailStorageBucket
          EMAIL_METADATA_TABLE: !Ref EmailMetadataTable
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # Lambda permission for S3 to invoke the function
  # Note: This permission is created here, but S3 notifications are configured by deploy.sh
  EmailProcessorS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EmailProcessorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${EmailStorageBucketName}-${AWS::AccountId}-${EnvironmentName}'

  # Note: S3 bucket notifications are configured automatically by deploy.sh after stack deployment
  # This avoids circular dependency issues in CloudFormation while ensuring proper configuration

  # SES Receipt Rule Set
  SESReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Sub 'auto-lab-email-rules-${EnvironmentName}'

  # SES Receipt Rule for incoming emails
  SESReceiptRule:
    Type: AWS::SES::ReceiptRule
    DependsOn: 
      - EmailStorageBucketPolicy
    Properties:
      RuleSetName: !Ref SESReceiptRuleSet
      Rule:
        Name: !Sub 'auto-lab-email-rule-${EnvironmentName}'
        Enabled: true
        Recipients:
          - !Ref MailReceivingAddress
        Actions:
          - S3Action:
              BucketName: !Ref EmailStorageBucket
              ObjectKeyPrefix: emails/

  # Lambda function to activate the SES receipt rule set (since CloudFormation doesn't support this directly)
  SESRuleSetActivatorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'ses-ruleset-activator-${EnvironmentName}'
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 60
      Role: !GetAtt SESRuleSetActivatorRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import json
          
          def lambda_handler(event, context):
              try:
                  ses_client = boto3.client('ses')
                  
                  if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
                      rule_set_name = event['ResourceProperties']['RuleSetName']
                      region = event['ResourceProperties']['Region']
                      
                      # Set the rule set as active
                      ses_client.set_active_receipt_rule_set(RuleSetName=rule_set_name)
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                     {'Message': f'Successfully activated rule set: {rule_set_name}'})
                  
                  elif event['RequestType'] == 'Delete':
                      # Don't deactivate on delete to avoid breaking other environments
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                     {'Message': 'Rule set activation not removed on delete'})
                  
              except Exception as e:
                  print(f'Error: {str(e)}')
                  cfnresponse.send(event, context, cfnresponse.FAILED, 
                                 {'Message': f'Failed to manage rule set: {str(e)}'})

  # IAM Role for the SES rule set activator function
  SESRuleSetActivatorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SESRuleSetAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SetActiveReceiptRuleSet
                  - ses:DescribeActiveReceiptRuleSet
                  - ses:ListReceiptRuleSets
                Resource: '*'

  # Custom resource to activate the SES receipt rule set
  SESRuleSetActivation:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: SESReceiptRule
    Properties:
      ServiceToken: !GetAtt SESRuleSetActivatorFunction.Arn
      RuleSetName: !Ref SESReceiptRuleSet
      Region: !Ref SesRegion

  # Custom resource function to configure S3 bucket notifications
  # This avoids circular dependency by configuring notifications after bucket and Lambda are created
  S3NotificationConfigurator:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 's3-notification-configurator-${EnvironmentName}'
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 60
      Role: !GetAtt S3NotificationConfiguratorRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import json
          
          def lambda_handler(event, context):
              try:
                  s3_client = boto3.client('s3')
                  
                  if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
                      bucket_name = event['ResourceProperties']['BucketName']
                      lambda_arn = event['ResourceProperties']['LambdaArn']
                      
                      # Configure S3 bucket notification
                      notification_config = {
                          'LambdaConfigurations': [
                              {
                                  'Id': 'EmailProcessorTrigger',
                                  'LambdaFunctionArn': lambda_arn,
                                  'Events': ['s3:ObjectCreated:*'],
                                  'Filter': {
                                      'Key': {
                                          'FilterRules': [
                                              {
                                                  'Name': 'prefix',
                                                  'Value': 'emails/'
                                              }
                                          ]
                                      }
                                  }
                              }
                          ]
                      }
                      
                      s3_client.put_bucket_notification_configuration(
                          Bucket=bucket_name,
                          NotificationConfiguration=notification_config
                      )
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                     {'Message': f'Successfully configured S3 notifications for: {bucket_name}'})
                  
                  elif event['RequestType'] == 'Delete':
                      bucket_name = event['ResourceProperties']['BucketName']
                      
                      # Remove S3 bucket notifications
                      s3_client.put_bucket_notification_configuration(
                          Bucket=bucket_name,
                          NotificationConfiguration={}
                      )
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                     {'Message': 'Successfully removed S3 notifications'})
                  
              except Exception as e:
                  print(f'Error: {str(e)}')
                  cfnresponse.send(event, context, cfnresponse.FAILED, 
                                 {'Message': f'Failed to configure S3 notifications: {str(e)}'})

  # IAM Role for the S3 notification configurator
  S3NotificationConfiguratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3NotificationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource: !GetAtt EmailStorageBucket.Arn

  # Custom resource to configure S3 bucket notifications
  EmailProcessorBucketNotification:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: 
      - EmailProcessorFunction
      - EmailProcessorS3Permission
      - EmailStorageBucket
    Properties:
      ServiceToken: !GetAtt S3NotificationConfigurator.Arn
      BucketName: !Ref EmailStorageBucket
      LambdaArn: !GetAtt EmailProcessorFunction.Arn

Outputs:
  EmailStorageBucket:
    Description: S3 bucket for storing received emails
    Value: !Ref EmailStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-EmailStorageBucket'

  EmailMetadataTable:
    Description: DynamoDB table for email metadata
    Value: !Ref EmailMetadataTable
    Export:
      Name: !Sub '${AWS::StackName}-EmailMetadataTable'

  EmailProcessorFunctionArn:
    Description: Email processor Lambda function ARN
    Value: !GetAtt EmailProcessorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EmailProcessorFunctionArn'

  SESReceiptRuleSet:
    Description: SES receipt rule set name
    Value: !Ref SESReceiptRuleSet
    Export:
      Name: !Sub '${AWS::StackName}-SESReceiptRuleSet'

  MailReceivingAddress:
    Description: Email address for receiving emails in this environment
    Value: !Ref MailReceivingAddress
    Export:
      Name: !Sub '${AWS::StackName}-MailReceivingAddress'
