AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auto Lab Solutions - SES Domain/Email Identities and Route53 DNS Records'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (development, production)
    Default: production
    AllowedValues:
      - development
      - production

  SesRegion:
    Type: String
    Description: AWS SES region
    Default: "ap-southeast-2"

  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID for the domain
    Default: ""

  DomainName:
    Type: String
    Description: The base domain name (e.g., autolabsolutions.com or dev.autolabsolutions.com)
    Default: "autolabsolutions.com"

Conditions:
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, ""]]

Resources:
  # SES Domain Identity for email receiving - CORRECT RESOURCE TYPE
  SESDomainIdentity:
    Type: AWS::SES::VerifiedEmailAddress
    Properties:
      EmailAddress: !Sub 'noreply@${DomainName}'

  # SES Domain Identity (using correct resource type)
  SESDomainVerification:
    Type: AWS::SES::DomainIdentity
    Properties:
      Domain: !Ref DomainName

  # SES Configuration Set for tracking
  SESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub 'auto-lab-config-set-${EnvironmentName}'

  # Route53 DNS Records (only if hosted zone is provided)
  # Domain Verification Record
  DomainVerificationRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '_amazonses.${DomainName}'
      Type: TXT
      TTL: 300
      ResourceRecords:
        - !Sub '"${SESDomainVerification}"'

  # MX Record for Email Receiving
  EmailReceivingMXRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: MX
      TTL: 300
      ResourceRecords:
        - !Sub '10 inbound-smtp.${SesRegion}.amazonses.com'

  # MAIL FROM Domain MX Record (for improved deliverability)
  MailFromMXRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'mail.${DomainName}'
      Type: MX
      TTL: 300
      ResourceRecords:
        - !Sub '10 feedback-smtp.${SesRegion}.amazonses.com'

  # SPF Record for MAIL FROM Domain
  MailFromSPFRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'mail.${DomainName}'
      Type: TXT
      TTL: 300
      ResourceRecords:
        - '"v=spf1 include:amazonses.com ~all"'

Outputs:
  SESDomainIdentity:
    Description: SES Domain Identity for email receiving
    Value: !Ref SESDomainVerification
    Export:
      Name: !Sub '${AWS::StackName}-SESDomainIdentity'

  SESVerifiedEmail:
    Description: SES Verified Email Address
    Value: !Ref SESDomainIdentity
    Export:
      Name: !Sub '${AWS::StackName}-SESVerifiedEmail'

  SESConfigurationSet:
    Description: SES Configuration Set
    Value: !Ref SESConfigurationSet
    Export:
      Name: !Sub '${AWS::StackName}-SESConfigurationSet'

  DomainName:
    Description: The domain name configured for SES
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
